version: '2'
services:
  person:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: none
      request_line: GET "/person/health" "HTTP/1.0"
      reinitializing_timeout: 60000
  mysql:
    scale: 1
    start_on_create: true

